=== hmrc/individuals-expenses-api/resources/public/api/conf/3.0/schemas/retrieve_employment_expenses_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Employment Expenses",
  "description": "Allows the retrieval of employment expenses",
  "type": "object",
  "properties": {
    "submittedOn": {
      "description": "The date the expenses were submitted.\n\nMust conform to the format YYYY-MM-DDThh:mm:ss.SSS'Z'",
      "type": "string",
      "example" : "2020-07-13T20:37:27.000Z"
    },
    "totalExpenses": {
      "description": "The sum of the expenses provided.\n\nThe value must be between  0 and 99999999999.99 up to 2 decimal places.",
      "type": "number",
      "multipleOf": 0.01,
      "minimum": 0,
      "maximum": 99999999999.99,
      "example" : 2000.99
    },
    "source": {
      "description": "Specifies the source of data returned.",
      "type": "string",
      "enum": [
        "hmrcHeld",
        "user"
      ]
    },
    "dateIgnored": {
      "description": "The date the expenses were flagged not to be used in the tax calculation.\n\nMust conform to the format YYYY-MM-DDThh:mm:ss.SSS'Z'",
      "type": "string",
      "example" : "2020-07-13T20:37:27.000Z"
    },
    "expenses": {
      "description": "Object containing the employment expenses.",
      "type": "object",
      "properties": {
        "businessTravelCosts": {
          "description": "Expenses associated with business travel where own or company vehicle was not used.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example" : 2000.99
        },
        "jobExpenses": {
          "description": "The actual expense of replacing or maintaining tools or special work clothes.\n\nThe value must be between  0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example" : 2000.99
        },
        "flatRateJobExpenses": {
          "description": "Fixed rate expenses applied for replacing or maintaining tools or special work clothes.\n\nThe value must be between  0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example" : 2000.99
        },
        "professionalSubscriptions": {
          "description": "Fees or subscriptions to professional bodies, required in order to undertake the employment.\n\nThe value must be between  0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example" : 2000.99
        },
        "hotelAndMealExpenses": {
          "description": "Subsistence costs incurred with work.\n\nThe value must be between  0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example" : 2000.99
        },
        "otherAndCapitalAllowances": {
          "description": "The expense from purchasing small items required for this employment.\n\nThe value must be between  0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example" : 2000.99
        },
        "vehicleExpenses": {
          "description": "Fuel and other costs when using a company vehicle.\n\nThe value must be between  0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example" : 2000.99
        },
        "mileageAllowanceRelief": {
          "description": "The shortfall incurred when the employer pays less than the approved mileage rate.\n\nThe value must be between  0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example" : 2000.99
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== hmrc/individuals-expenses-api/resources/public/api/conf/3.0/examples/retrieve_employment_expenses/hmrc_held.json
{
  "submittedOn": "2020-12-12T12:12:12Z",
  "totalExpenses": 123.12,
  "source": "hmrcHeld",
  "dateIgnored": "2020-12-11T12:12:12Z",
  "expenses": {
    "businessTravelCosts": 123.12,
    "jobExpenses": 123.12,
    "flatRateJobExpenses": 123.12,
    "professionalSubscriptions": 123.12,
    "hotelAndMealExpenses": 123.12,
    "otherAndCapitalAllowances": 123.12,
    "vehicleExpenses": 123.12,
    "mileageAllowanceRelief": 123.12
  }
}
